#!/usr/bin/env bash

# Name:          Kill
# Description:   Sends a SIGKILL signal to the first process whose name
#                matches the provided argument.
# Options:       None.
# Created on:    13-02-2018
# Last modified: 13-02-2018
# Author:        Adam Szczerbiak, szczerbiakadam@gmail.com
# License:       MIT


SCRIPT_NAME="$(basename "${0}")"

if [ "${#}" -lt 1 ]; then
  >&2 echo "Error: please specify the name of the process to kill."
  exit 2
fi

maybe_pid="$(ps aux | grep "${1}" | grep -v "${SCRIPT_NAME}" | grep -v "grep")"

if [ "${?}" -ne 0 ]; then
  >&2 printf "Error: process named \"%s\" is not running.\n" "${1}"
  exit 1
fi

pid="$(echo "${maybe_pid}" | awk '{print $2}')"

kill -9 "${pid}"
if [ "${?}" -eq 0 ]; then
  printf "Successfully killed \"%s\" (pid: %s).\n" "${1}" "${pid}"
fi
